# Generated by Django 3.1.4 on 2020-12-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20201220_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fredquerydata',
            name='end_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fredquerydata',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
