# Generated by Django 3.1.4 on 2020-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_auto_20201221_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fredquerydata',
            name='end_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fredquerydata',
            name='start_date',
            field=models.DateField(max_length=50),
        ),
    ]
